"""Question bank for the Visual Prompt questionnaire app."""

from __future__ import annotations

from typing import Any


Question = dict[str, Any]
Option = dict[str, str]


def make_option(code: str, label: str, description: str, prompt_fragment: str, glossary: str) -> Option:
    return {
        "code": code,
        "label": label,
        "description": description,
        "prompt_fragment": prompt_fragment,
        "glossary": glossary,
    }


QUESTION_BANK: list[Question] = [
    {
        "id": "input_mode",
        "section": "基础设置",
        "title": "你这次是从零生成图片，还是基于已有图片改图？",
        "type": "single",
        "output_field": "Input Mode",
        "options": [
            make_option("A", "文生图", "从文字描述直接生成图片。", "text-to-image, prompt-first workflow", "Text-to-image: 从文字直接生成图像。"),
            make_option("B", "图生图或改图", "基于参考图重构画面。", "image-to-image, preserve key visual identity", "Image-to-image: 在保留要素基础上重绘。"),
            make_option("C", "多图参考融合", "融合主体/风格/构图等多张参考图。", "multi-reference fusion, combine subject and style references", "多图参考融合: 不同参考图控制不同维度。"),
        ],
    },
    {
        "id": "purpose",
        "section": "基础设置",
        "title": "这张图主要用来做什么？",
        "type": "single",
        "output_field": "Purpose",
        "options": [
            make_option("A", "头像或人物肖像", "重视脸部和身份识别。", "portrait-focused, identity recognition", "Portrait: 重点是人物识别。"),
            make_option("B", "表情包或贴纸", "重视夸张表情和小尺寸可读性。", "reaction sticker, bold expression, high readability", "Sticker: 轮廓清晰、背景简单。"),
            make_option("C", "海报或封面", "重视视觉冲击和标题空间。", "poster composition, strong focal hierarchy, title-safe area", "Poster: 需要完整构图和焦点。"),
            make_option("D", "插画或故事场景", "重视叙事和氛围。", "story illustration, environmental storytelling", "Scene illustration: 主体与环境共同叙事。"),
            make_option("E", "信息图/地图/蓝图", "重视结构、标注和可读性。", "infographic clarity, labeled structure, map/blueprint logic", "Infographic: 重点是信息表达。"),
            make_option("F", "产品或物体展示", "重视轮廓、结构和商业展示感。", "product showcase, clean silhouette, material clarity", "Product visual: 强调轮廓与材质。"),
        ],
    },
    {
        "id": "subject_type",
        "section": "基础设置",
        "title": "画面的主要对象是什么？",
        "type": "single",
        "output_field": "Subject",
        "options": [
            make_option("A", "单个人物", "适合头像、肖像和人物卡通化。", "single character focus", "Single character: 易聚焦身份与表情。"),
            make_option("B", "多个人物", "适合关系图、团队图和群像。", "group portrait, relationship-aware composition", "Group portrait: 强调站位和关系。"),
            make_option("C", "单个物体或产品", "适合商品、图标、道具。", "single object focus, product-centric framing", "Object-focused: 突出结构和材质。"),
            make_option("D", "建筑或地点", "适合城市、景点和建筑外观。", "architecture/location illustration", "Location-based: 重点是空间与地标。"),
            make_option("E", "完整场景", "主体和环境共同构成叙事。", "full scene storytelling", "Full scene: 场景信息和氛围更重要。"),
            make_option("F", "抽象概念", "用符号、颜色和构图表达想法。", "abstract concept visualization", "Abstract concept: 非具象表达。"),
        ],
    },
    {
        "id": "priority",
        "section": "基础设置",
        "title": "你最希望这张图优先满足哪一点？",
        "type": "single",
        "output_field": "Priority",
        "options": [
            make_option("A", "像不像", "优先保留身份、脸型、发型或结构。", "identity fidelity first", "Identity fidelity: 强调像原对象。"),
            make_option("B", "风格统一", "优先确保画面视觉语言一致。", "style consistency first", "Consistency: 避免拼凑感。"),
            make_option("C", "清楚易读", "优先保证小尺寸和复杂场景中的可读性。", "readability first", "Readability: 快速看懂重点。"),
            make_option("D", "情绪到位", "优先表达氛围和心理感受。", "mood delivery first", "Mood-first: 强化整体情绪。"),
            make_option("E", "适合传播", "优先抓眼、简洁、易懂。", "shareability first, eye-catching simplicity", "Shareability: 第一眼吸引力。"),
        ],
    },
    {
        "id": "aspect_ratio",
        "section": "基础设置",
        "title": "你希望图片是什么比例？",
        "type": "single",
        "output_field": "Aspect Ratio",
        "options": [
            make_option("A", "1:1 正方形", "适合头像、贴纸和社交媒体图。", "square 1:1 framing", "Square ratio: 稳定、通用。"),
            make_option("B", "3:2 横版", "适合多人图和场景图。", "landscape 3:2 framing", "Landscape: 适合关系和环境。"),
            make_option("C", "2:3 竖版", "适合人物海报和手机壁纸。", "portrait 2:3 framing", "Portrait ratio: 适合人物和海报。"),
            make_option("D", "16:9 宽屏", "适合电影感场景和横向海报。", "cinematic widescreen 16:9", "Widescreen: 电影感更强。"),
            make_option("E", "9:16 竖屏", "适合短视频封面和手机屏幕。", "vertical 9:16 framing", "Vertical short-form: 适合移动端。"),
            make_option("F", "自动比例", "让模型根据内容自行决定。", "auto aspect ratio based on composition", "Auto ratio: 给模型更多自由。"),
        ],
    },
    {
        "id": "medium",
        "section": "风格定义",
        "title": "你希望这张图整体接近哪种媒介？",
        "type": "single",
        "output_field": "Style Family",
        "options": [
            make_option("A", "摄影或电影剧照", "接近真实镜头语言。", "cinematic photography style, lens depth cues", "Cinematic style: 强调镜头和光影。"),
            make_option("B", "编辑插画", "像杂志/媒体配图，风格克制。", "editorial illustration style", "Editorial illustration: 概念清晰、控制克制。"),
            make_option("C", "卡通或漫画", "强调轮廓、表情和动作。", "cartoon/comic style, expressive silhouette", "Cartoon: 轮廓和表情优先。"),
            make_option("D", "动漫或赛璐璐动画", "线条干净，阴影块面明确。", "anime cel-shaded style, clean line art", "Cel animation: 清晰线条+块面阴影。"),
            make_option("E", "矢量平面设计", "几何化色块和清晰边界。", "vector flat design, geometric blocks", "Vector style: 边缘干净、可缩放感。"),
            make_option("F", "技术图或蓝图", "重视结构线稿和标注。", "technical blueprint style, diagram precision", "Blueprint: 结构表达优先。"),
            make_option("G", "3D 玩具或手办", "强调体积和材质。", "stylized 3D toy aesthetic", "Toy-like 3D: 材质和造型可爱化。"),
            make_option("H", "拼贴或混合媒介", "混合照片/纸张/纹理等材料。", "mixed-media collage aesthetic", "Mixed media: 多种材料拼接。"),
        ],
    },
    {
        "id": "realism_level",
        "section": "风格定义",
        "title": "你希望整体真实程度处于哪一档？",
        "type": "single",
        "output_field": "Realism Level",
        "options": [
            make_option("A", "高度写实", "尽量像真实照片。", "photorealistic, realistic texture and lighting", "Photorealistic: 照片级写实。"),
            make_option("B", "半写实", "保留真实结构并艺术化处理。", "semi-realistic with artistic stylization", "Semi-realistic: 写实与风格化折中。"),
            make_option("C", "明显风格化", "追求视觉语言而非照片真实性。", "stylized illustration-forward rendering", "Stylized: 服从风格而非真实。"),
            make_option("D", "高度简化", "只保留关键特征并减少细节。", "highly simplified forms, reduced detail", "Highly simplified: 大幅降细节。"),
            make_option("E", "图标化/符号化", "接近图形符号表达。", "iconic symbolic rendering", "Icon-like: 以轮廓和符号识别。"),
        ],
    },
    {
        "id": "composition",
        "section": "画面控制",
        "title": "你希望画面如何组织？",
        "type": "single",
        "output_field": "Composition",
        "options": [
            make_option("A", "居中对称", "主体稳定、正式、清楚。", "centered symmetrical composition", "Centered composition: 稳定清晰。"),
            make_option("B", "轻微偏置", "不完全居中，更自然。", "slightly off-center composition", "Off-center: 更自然有呼吸感。"),
            make_option("C", "动态斜线构图", "通过斜向元素制造动感。", "dynamic diagonal composition", "Diagonal composition: 强化动势和张力。"),
            make_option("D", "网格式排布", "多元素按网格组织。", "grid-based layout", "Grid layout: 强调秩序与可读性。"),
            make_option("E", "海报式构图", "预留标题和视觉焦点。", "poster-style focal hierarchy", "Poster composition: 适合封面与标题。"),
            make_option("F", "拼贴式构图", "元素叠加，信息密集。", "collage composition with layered elements", "Collage composition: 实验性强。"),
        ],
    },
    {
        "id": "camera_angle",
        "section": "画面控制",
        "title": "你希望观众从什么角度看主体？",
        "type": "single",
        "output_field": "Camera / View",
        "options": [
            make_option("A", "正面视角", "直接清晰，适合头像和表情包。", "front view", "Front view: 识别度高。"),
            make_option("B", "三分之四视角", "兼顾正面与侧面立体感。", "three-quarter view", "Three-quarter view: 常见角色角度。"),
            make_option("C", "侧面视角", "突出轮廓和动作方向。", "side profile view", "Side view: 轮廓表达更强。"),
            make_option("D", "俯视或仰视", "增强戏剧性和视觉冲击。", "high-angle or low-angle dramatic view", "High/low angle: 强化戏剧感。"),
            make_option("E", "正交视图", "不强调透视，适合制图。", "orthographic view, no perspective distortion", "Orthographic: 工程与说明图常用。"),
            make_option("F", "等距视角", "有三维感但透视较弱。", "isometric view", "Isometric: 游戏地图与建筑常用。"),
        ],
    },
    {
        "id": "subject_scale",
        "section": "画面控制",
        "title": "主体在画面中应该占多大？",
        "type": "single",
        "output_field": "Subject Scale",
        "options": [
            make_option("A", "特写", "只看脸或局部，情绪强。", "close-up framing", "Close-up: 强情绪，弱背景。"),
            make_option("B", "半身", "兼顾表情、手势和服装。", "half-body framing", "Half-body: 人物图稳妥方案。"),
            make_option("C", "全身", "突出姿态和角色轮廓。", "full-body framing", "Full-body: 强调姿态与服饰。"),
            make_option("D", "主体加环境", "主体和环境共同提供信息。", "subject with supporting environment", "Subject+environment: 平衡叙事。"),
            make_option("E", "场景优先", "环境是主角，主体为场景一部分。", "environment-dominant composition", "Scene-first: 适合世界观和地图。"),
        ],
    },
    {
        "id": "linework",
        "section": "风格定义",
        "title": "你希望线条是什么感觉？",
        "type": "single",
        "output_field": "Linework",
        "options": [
            make_option("A", "粗而干净", "轮廓明确，适合卡通和贴纸。", "bold clean outlines, consistent line weight", "Bold line: 卡通和贴纸高可读性。"),
            make_option("B", "细而稳定", "精致且克制。", "thin controlled linework", "Fine line: 细腻感更强。"),
            make_option("C", "几乎无线稿", "主要靠色块和形体塑造。", "minimal line art, shape-and-light driven", "Line-minimal: 靠色块和体积。"),
            make_option("D", "手绘草图感", "线条自然不规则。", "sketchy hand-drawn line quality", "Sketchy line: 随手感和人味。"),
            make_option("E", "技术制图线", "精确克制，类似工程图。", "technical drafting linework", "Technical line: 工程说明风格。"),
            make_option("F", "墨线或版画感", "黑白对比强，有传统印刷感。", "inked linocut/printmaking line style", "Printmaking line: 粗黑线和强反差。"),
        ],
    },
    {
        "id": "shape_language",
        "section": "风格定义",
        "title": "主体的形状应该偏向哪种？",
        "type": "single",
        "output_field": "Shape Language",
        "options": [
            make_option("A", "圆润", "友好、可爱、亲和。", "rounded shapes, soft geometry", "Rounded shapes: 更亲和。"),
            make_option("B", "几何化", "基础几何形组织画面。", "geometric shape language", "Geometric: 设计感更强。"),
            make_option("C", "自然有机", "更接近真实生长形态。", "organic natural forms", "Organic forms: 更自然不规则。"),
            make_option("D", "夸张变形", "放大关键部位强化表达。", "controlled exaggeration of proportions", "Exaggeration: 卡通表达核心手段。"),
            make_option("E", "极简符号化", "只保留最关键轮廓。", "minimal symbolic silhouettes", "Symbolic: 接近图标逻辑。"),
        ],
    },
    {
        "id": "detail_level",
        "section": "风格定义",
        "title": "细节应该保留多少？",
        "type": "single",
        "output_field": "Detail Level",
        "options": [
            make_option("A", "尽量保留细节", "适合写实肖像和产品图。", "retain rich detail and micro-features", "High detail: 更接近现实。"),
            make_option("B", "保留主要身份特征", "保留发型、脸型、服装轮廓等。", "preserve key identity cues", "Identity cues: 识别优先。"),
            make_option("C", "只保留关键识别点", "保留最容易认出的线索。", "retain only primary recognition cues", "Recognition cues: 进一步压缩细节。"),
            make_option("D", "大幅简化", "看得出类型和动作即可。", "aggressive simplification, reduced micro-detail", "Aggressive simplification: 更像设计稿。"),
            make_option("E", "接近符号", "基本靠轮廓、颜色和构图表达。", "symbolic abstraction with minimal detail", "Symbolic abstraction: 细节非核心。"),
        ],
    },
    {
        "id": "color_scheme",
        "section": "风格定义",
        "title": "你希望颜色如何组织？",
        "type": "single",
        "output_field": "Color",
        "options": [
            make_option("A", "高饱和高对比", "醒目强烈，适合社交媒体。", "high saturation, high contrast palette", "High sat/high contrast: 抓眼强。"),
            make_option("B", "低饱和柔和", "安静克制，偏高级插画。", "muted soft palette", "Muted palette: 更克制。"),
            make_option("C", "有限色板", "少量颜色建立统一感。", "limited palette, disciplined color set", "Limited palette: 统一性强。"),
            make_option("D", "黑白或单色系", "强调结构和图形感。", "monochrome or black-and-white treatment", "Monochrome: 聚焦结构。"),
            make_option("E", "复古色调", "带年代感和胶片气质。", "retro palette with nostalgic tone", "Retro tone: 有年代氛围。"),
            make_option("F", "自定义品牌色", "根据指定品牌主色组织画面。", "brand-color-driven palette", "Brand palette: 对齐品牌识别。"),
        ],
    },
    {
        "id": "lighting",
        "section": "风格定义",
        "title": "你希望光影怎么处理？",
        "type": "single",
        "output_field": "Lighting",
        "options": [
            make_option("A", "自然真实光影", "接近真实摄影光照。", "natural realistic lighting", "Natural light: 写实导向。"),
            make_option("B", "戏剧化光影", "明暗反差强，情绪浓。", "dramatic chiaroscuro lighting", "Dramatic light: 情绪冲击大。"),
            make_option("C", "平涂", "不强调真实明暗。", "flat color lighting approach", "Flat color: 扁平插画常用。"),
            make_option("D", "少量赛璐璐阴影", "清晰边界阴影块。", "subtle cel shading", "Cel shading: 动画块面阴影。"),
            make_option("E", "几乎无光影", "适合图解和极简视觉。", "minimal to no shading", "No-shading: 图解和符号化。"),
            make_option("F", "霓虹或边缘光", "科技/夜景/赛博氛围。", "neon rim light accents", "Rim light: 轮廓强化。"),
        ],
    },
    {
        "id": "texture",
        "section": "风格定义",
        "title": "画面表面质感应该是什么？",
        "type": "single",
        "output_field": "Texture",
        "options": [
            make_option("A", "干净矢量感", "边缘干净，没有纸纹笔触。", "clean vector finish", "Vector finish: 数字化且干净。"),
            make_option("B", "轻微纸张纹理", "更像出版物和纸面插画。", "subtle paper grain texture", "Paper grain: 提升印刷感。"),
            make_option("C", "手绘笔触", "可见笔刷和颜料痕迹。", "visible hand-painted brush texture", "Brush texture: 手工感更强。"),
            make_option("D", "胶片颗粒", "细微颗粒和复古摄影感。", "film grain overlay", "Film grain: 复古摄影语感。"),
            make_option("E", "丝网印刷/Risograph", "错位颗粒和独立出版感。", "risograph print texture, slight misregistration", "Risograph: 套色偏移与颗粒。"),
            make_option("F", "3D 材质", "表现黏土/玻璃/金属等材质。", "stylized 3D material rendering", "3D material: 体积和材质导向。"),
            make_option("G", "技术网格", "网格背景和辅助结构线。", "technical grid background", "Technical grid: 蓝图与工程说明常用。"),
        ],
    },
    {
        "id": "mood",
        "section": "画面控制",
        "title": "你希望画面是什么情绪？",
        "type": "single",
        "output_field": "Mood",
        "options": [
            make_option("A", "冷静专业", "理性、稳重、可信。", "calm professional mood", "Professional mood: 商业与技术常用。"),
            make_option("B", "温暖友好", "亲和、舒适、有温度。", "warm friendly tone", "Warm mood: 人物与生活方式适配。"),
            make_option("C", "可爱活泼", "轻松、可爱、社交友好。", "cute playful tone", "Playful mood: 贴纸表情包常用。"),
            make_option("D", "幽默荒诞", "不合常理但有趣。", "humorous absurd vibe", "Absurd humor: 强表达和传播性。"),
            make_option("E", "神秘梦幻", "朦胧、幻想、超现实。", "mystical dreamlike atmosphere", "Dreamlike mood: 概念图常用。"),
            make_option("F", "威严强势", "力量感和权威感。", "powerful authoritative mood", "Authoritative mood: 主视觉/史诗感。"),
            make_option("G", "紧张压迫", "压抑、风险、危机。", "tense oppressive atmosphere", "Tense mood: 悬疑和风险主题。"),
        ],
    },
    {
        "id": "background_complexity",
        "section": "画面控制",
        "title": "背景应该多复杂？",
        "type": "single",
        "output_field": "Background",
        "options": [
            make_option("A", "纯色或透明背景", "主体最突出。", "solid or transparent background", "Solid/transparent: 适合头像贴纸。"),
            make_option("B", "极简符号背景", "少量符号和装饰。", "minimal symbolic background", "Minimal symbolic: 不抢主体。"),
            make_option("C", "简单场景背景", "有环境信息但不复杂。", "simple contextual background", "Simple scene: 轻叙事。"),
            make_option("D", "完整环境背景", "背景承担叙事和氛围。", "fully developed environmental background", "Full environment: 场景表达更完整。"),
            make_option("E", "图解式背景", "网格、箭头、标注等结构元素。", "diagrammatic background with guides/labels", "Diagrammatic background: 信息解释导向。"),
            make_option("F", "抽象图形背景", "几何和色块构成氛围。", "abstract geometric background", "Abstract background: 非具象氛围。"),
        ],
    },
    {
        "id": "additional_elements",
        "section": "画面控制",
        "title": "画面是否需要额外元素？",
        "type": "single",
        "output_field": "Additional Elements",
        "options": [
            make_option("A", "不需要", "保持干净。", "no additional elements", "No extras: 画面更纯净。"),
            make_option("B", "简单符号", "问号、感叹号、星星等。", "simple symbols (question mark, spark, action lines)", "Simple symbols: 强化表情和语义。"),
            make_option("C", "文字标题", "用于海报和封面。", "title text area reserved", "Title text: 封面传播常用。"),
            make_option("D", "对话框或气泡", "用于漫画和社交表达。", "speech bubbles or comic callouts", "Speech bubble: 漫画语法。"),
            make_option("E", "箭头和标注", "用于技术图和说明图。", "arrows and annotation callouts", "Callout: 图解说明核心元素。"),
            make_option("F", "多视图小窗", "展示局部或侧面细节。", "inset multi-view windows", "Inset view: 结构展示更完整。"),
        ],
    },
    {
        "id": "preserve_items",
        "section": "画面控制",
        "title": "如果是基于图片改图，最需要保留哪些内容？（可多选）",
        "type": "multi",
        "output_field": "Preserve",
        "options": [
            make_option("A", "姿势和动作", "保持原图姿态和动作方向。", "preserve pose and gesture", "Pose preservation: 保留动作识别。"),
            make_option("B", "构图和主体位置", "保持主体位置和布局。", "preserve composition and subject placement", "Composition preservation: 保留版式逻辑。"),
            make_option("C", "发型和脸型", "保留人物身份识别核心。", "preserve hairstyle and face shape", "Identity core: 头像识别关键。"),
            make_option("D", "服装轮廓", "保留服饰和职业特征。", "preserve clothing silhouette", "Clothing cue: 保留角色属性。"),
            make_option("E", "表情情绪", "保留思考/惊讶等情绪方向。", "preserve expression and emotional tone", "Expression cue: 保留情绪语义。"),
            make_option("F", "颜色关系", "保留主色调和颜色关系。", "preserve core color relationships", "Color relation: 延续视觉识别。"),
            make_option("G", "只保留身份线索，允许大幅重构", "优先识别线索，其它可重画。", "preserve identity cues only, allow major reconstruction", "Reconstruction-friendly: 保留认人即可。"),
        ],
    },
    {
        "id": "avoid_items",
        "section": "画面控制",
        "title": "你最不希望图片出现什么问题？（可多选）",
        "type": "multi",
        "output_field": "Avoid",
        "options": [
            make_option("A", "照片滤镜感", "看起来只是套滤镜，不像重构。", "avoid photo-filter look", "Photo-filter look: 改图常见失败模式。"),
            make_option("B", "诡异脸或诡异手", "避免不自然面部和手部变形。", "avoid uncanny face/hands", "Uncanny valley: 接近真实但不自然。"),
            make_option("C", "过度写实", "不要太像照片。", "avoid over-photorealism", "Avoid photoreal: 保持风格化。"),
            make_option("D", "过度幼稚", "避免太像儿童画。", "avoid childish oversimplification", "Maturity control: 保持设计感。"),
            make_option("E", "画面太复杂", "避免元素过多、重点不清。", "avoid cluttered composition", "Clutter: 降低可读性。"),
            make_option("F", "画面太平", "避免缺少焦点与情绪。", "avoid flat lifeless composition", "Flatness: 缺少视觉张力。"),
            make_option("G", "不要动漫风", "避免日式动漫特征。", "exclude anime-specific traits", "Anime exclusion: 控制风格偏移。"),
            make_option("H", "不要 3D 渲染感", "避免建模软件/塑料玩具效果。", "exclude 3D render aesthetic", "No 3D render: 保持平面感。"),
            make_option("I", "不要文字", "避免生成错误文字内容。", "no generated text", "No text: 减少错字风险。"),
            make_option("J", "不要模仿特定艺术家或版权角色", "避免侵权和 IP 风险。", "avoid living-artist imitation and copyrighted characters", "IP-safe: 避免版权和风格挪用。"),
        ],
    },
    {
        "id": "tuning_strength",
        "section": "画面控制",
        "title": "你愿意接受多大程度的风格改动？",
        "type": "single",
        "output_field": "Tuning Strength",
        "options": [
            make_option("A", "很保守", "尽量保留原对象，仅轻微风格化。", "very conservative transformation", "Conservative: 像原图优先。"),
            make_option("B", "轻度重构", "保留大部分结构并明显美术化。", "light reconstruction", "Light reconstruction: 稳定且有风格。"),
            make_option("C", "中度重构", "可识别但视觉语言明显改变。", "moderate reconstruction", "Moderate reconstruction: 平衡像与风格。"),
            make_option("D", "强风格化", "大幅简化与重画。", "strong stylization and redraw", "Strong stylization: 传播性更强。"),
            make_option("E", "极端抽象", "只保留概念或关键符号。", "extreme abstraction", "Extreme abstraction: 实验视觉导向。"),
        ],
    },
]


TUNING_KNOBS: list[dict[str, str]] = [
    {
        "name": "Abstraction Level",
        "cn": "抽象程度",
        "desc": "越高越不像照片，越低越接近真实。",
    },
    {
        "name": "Line Weight",
        "cn": "线条粗细",
        "desc": "越粗越卡通，越细越精致。",
    },
    {
        "name": "Exaggeration",
        "cn": "夸张程度",
        "desc": "影响表情、比例和动作。",
    },
    {
        "name": "Detail Density",
        "cn": "细节密度",
        "desc": "影响脸部、衣服、背景和纹理。",
    },
    {
        "name": "Color Contrast",
        "cn": "色彩对比",
        "desc": "影响抓眼程度和可读性。",
    },
    {
        "name": "Background Complexity",
        "cn": "背景复杂度",
        "desc": "影响主体突出程度。",
    },
    {
        "name": "Identity Preservation",
        "cn": "身份保留程度",
        "desc": "影响图生图时像不像原人物。",
    },
    {
        "name": "Texture Strength",
        "cn": "纹理强度",
        "desc": "影响干净数字风和纸张手绘感的比例。",
    },
]
