"""Small DeepSeek-backed Markdown summarizer."""

from .deepseek import (
    DEFAULT_BASE_URL,
    DEFAULT_MODEL,
    LENGTH_CAPTIONS,
    LENGTH_INSTRUCTIONS,
    LENGTH_LABELS,
    LENGTH_TARGETS,
    MAX_CUSTOM_INSTRUCTION_CHARACTERS,
    MAX_SOURCE_CHARACTERS,
    MODE_CAPTIONS,
    MODE_INSTRUCTIONS,
    MODE_LABELS,
    STYLE_CAPTIONS,
    STYLE_INSTRUCTIONS,
    STYLE_LABELS,
    SYSTEM_PROMPT,
    SummaryError,
    SummaryDocument,
    SummaryItem,
    SummaryResult,
    SummarySection,
    build_messages,
    build_prompt_template,
    parse_summary_document,
    summarize_markdown,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "DEFAULT_MODEL",
    "LENGTH_CAPTIONS",
    "LENGTH_INSTRUCTIONS",
    "LENGTH_LABELS",
    "LENGTH_TARGETS",
    "MAX_CUSTOM_INSTRUCTION_CHARACTERS",
    "MAX_SOURCE_CHARACTERS",
    "MODE_CAPTIONS",
    "MODE_INSTRUCTIONS",
    "MODE_LABELS",
    "STYLE_CAPTIONS",
    "STYLE_INSTRUCTIONS",
    "STYLE_LABELS",
    "SYSTEM_PROMPT",
    "SummaryError",
    "SummaryDocument",
    "SummaryItem",
    "SummaryResult",
    "SummarySection",
    "build_messages",
    "build_prompt_template",
    "parse_summary_document",
    "summarize_markdown",
]
